/**
 * @file ir_servo.c
 * @brief Timer-based IR sensor and servo control system implementation
 * @reference Draft generated by Claude Sonnet3.7, adjusted by Shanghong Lin @BUILD1
 * 
 * This module implements a state machine approach to control the
 * servo and motor movements based on IR sensor detection and weight readings.
 * 
 */

#include "ir_servo.h"
#include "mcc_generated_files/system/system.h"
#include "nrf24_lib.h"
#include <string.h>
#include <stdio.h>

// Current state of the IR servo state machine
static volatile ir_servo_state_t irServoState = IR_STATE_IDLE;

// Counter of detected objects
static volatile uint8_t itemNbr = 0;

// Weight sensor value
static volatile int16_t itemWeight = 0;

// Weight threshold values
static uint16_t weightMin = WEIGHT_MIN;
static uint16_t weightMax = WEIGHT_MAX;

// Buffer for NRF24 communication
static unsigned char bufferTX[32];



/**
 * Load the new duty cycle to both slices
 */
void reload_PWM1_dutyCycle(double slice1, double slice2)
{
    PWM1_16BIT_LoadBufferRegisters();
    PWM1_16BIT_SetSlice1Output1DutyCycleRegister(DUTYCYCLE_RATIO_CONVERT(slice1));
    PWM1_16BIT_SetSlice1Output2DutyCycleRegister(DUTYCYCLE_RATIO_CONVERT(slice2));
}

/**
 * Configure and start TMR0 with specified parameters
 */
static void TMR0_ConfigureAndStart(uint8_t period, uint8_t prescale, uint8_t postscale, uint8_t clockSource)
{
    // Stop the timer before configuration
    TMR0_Stop();
    
    // Set the period value
    TMR0H = period;
    
    // Reset the counter
    TMR0L = 0;
    
    // Configure clock source and prescaler
    T0CON1 = (clockSource << _T0CON1_T0CS_POSN) | 
             (prescale << _T0CON1_T0CKPS_POSN) |
             (1 << _T0CON1_T0ASYNC_POSN);  // T0ASYNC not_synchronised
    
    // Configure postscaler and mode (8-bit)
    T0CON0 = (postscale << _T0CON0_T0OUTPS_POSN) |
             (0 << _T0CON0_T0MD16_POSN);  // 8-bit mode
    
    // Clear interrupt flag
    PIR3bits.TMR0IF = 0;
    
    // Enable interrupt (if needed)
    PIE3bits.TMR0IE = 1;
    
    // Start the timer
    TMR0_Start();
}

/**
 * Called when IR sensor detects an object
 */
void ir_servo_start(void)
{
    // Ignore if we're already processing an item
    if (irServoState != IR_STATE_IDLE) {
        // Clear the interrupt flag and EXIT
        EXT_INT1_InterruptFlagClear();
        return;
    }
    
    // Stop any existing timer operation
    TMR0_Stop();
    // Increment item counter
    itemNbr++;
    (void) printf("itemNumber: %d\r\n", itemNbr);
    
    // Change state and start timer for 1000ms (wait for object to reach detection zone)
    irServoState = IR_STATE_WEIGHT_READ;
    TMR0_ConfigureAndStart(0x79, 4, 15, 4); 
    // Period: 1000ms = ~(1/31k)*16*16*121, with prescale = postscale = 1:16
}

/**
 * Read the weight sensor and determine acceptance/rejection
 */
static void ir_servo_weight_read(void)
{
    // Note that when the object moves to the detection zone,
    // the motor won't stop, assume that the system can read the weight
    // while the object is moving.
    // Stop the motor here if necessary.
    
    // Read the weight sensor value
    ADC_SampleCapacitorDischarge();
    itemWeight = ADC_ChannelSelectAndConvert(ADC_CHANNEL_ANA0);
    (void) printf("itemWeight %d\r\n", itemWeight);
    
    // Enter different state based on itemWeight
    if (itemWeight >= weightMin && itemWeight <= weightMax)
    {
        // Item is accepted - send data and return to idle state
        memset(bufferTX, 0, sizeof(bufferTX));
        sprintf((char*)bufferTX, "%d,%d,%s", itemNbr, itemWeight, "ACC");
        nrf24_send_rf_data(bufferTX);
        printf("[Send] Data: %d,%d,%s\n", itemNbr, itemWeight, "ACC");
        
        (void) printf("itemWeight is ACCEPTED\n");
        (void) printf("\n");
        
        // Process complete, return to idle state
        irServoState = IR_STATE_IDLE;
        // Clear the interrupt flag that may be set by the unstable signal transition
        // from low to high of the IR-Sensor.
        EXT_INT1_InterruptFlagClear();
    }
    else
    {
        // Item is rejected - start rejection sequence
        (void) printf("itemWeight is REJECTED\n");
        
        // Send rejection data
        memset(bufferTX, 0, sizeof(bufferTX));
        sprintf((char*)bufferTX, "%d,%d,%s", itemNbr, itemWeight, "REJ");
        nrf24_send_rf_data(bufferTX);
        printf("[Send] Data: %d,%d,%s\n", itemNbr, itemWeight, "REJ");
        
        // STEP1: Servo:IDLE, Motor:STOP
        reload_PWM1_dutyCycle(SERVO_IDLE, 0);
        
        // Change state and start timer for 500ms
        irServoState = IR_STATE_REJECT_STEP1;
        TMR0_ConfigureAndStart(0x3C, 4, 15, 4); 
        // Period: 500ms = ~(1/31k)*16*16*60, with prescale = postscale = 1:16
    }
}

/**
 * Rejection process Step 1 -> Step 2
 */
static void ir_servo_reject_step1(void)
{
    // STEP2: Servo:PUSH, Motor:STOP
    reload_PWM1_dutyCycle(SERVO_PUSH, 0);
    
    // Change state and start timer for 2000ms
    irServoState = IR_STATE_REJECT_STEP2;
    TMR0_ConfigureAndStart(0xF2, 4, 15, 4); 
    // Period: 2000ms = ~(1/31k)*16*16*242, with prescale = postscale = 1:16
}

/**
 * Rejection process Step 2 -> Step 3
 */
static void ir_servo_reject_step2_3(void)
{
    if (irServoState == IR_STATE_REJECT_STEP2) {
        // Start second period for remaining ~1000ms
        TMR0_ConfigureAndStart(0x79, 4, 15, 4); 
        // Period: 1000ms = ~(1/31k)*16*16*121, with prescale = postscale = 1:16
        irServoState = IR_STATE_REJECT_STEP3;
    } else {
        // STEP3: Servo:IDLE, Motor:FAST
        reload_PWM1_dutyCycle(SERVO_IDLE, MOTOR_FAST);
        
        // Process complete
        irServoState = IR_STATE_COMPLETE;
        TMR0_ConfigureAndStart(0xFE, 0, 0, 4); // Minimal delay
        // Period: 8ms = ~(1/31k)*1*1*254, with prescale = postscale = 1:1
    }
}

/**
 * Complete the rejection process
 */
static void ir_servo_complete(void)
{
    // Clear interrupt flag and prepare for next detection,
    // as the interrupt flag that may be set by the unstable signal transition
    // from low to high of the IR-Sensor.
    EXT_INT1_InterruptFlagClear();
    (void) printf("\n");
    
    // Return to idle state
    irServoState = IR_STATE_IDLE;
}

/**
 * TMR0 interrupt handler to manage IR servo state machine
 */
static void TMR0_IRQHandler(void)
{
    // Reset timer interrupt flag
    PIR3bits.TMR0IF = 0;
    
    // Execute the appropriate function based on current state
    switch (irServoState)
    {
        case IR_STATE_WEIGHT_READ:
            ir_servo_weight_read();
            break;
            
        case IR_STATE_REJECT_STEP1:
            ir_servo_reject_step1();
            break;
            
        case IR_STATE_REJECT_STEP2:
        case IR_STATE_REJECT_STEP3:
            ir_servo_reject_step2_3();
            break;
            
        case IR_STATE_COMPLETE:
            ir_servo_complete();
            break;
            
        case IR_STATE_IDLE:
        default:
            // Nothing to do in idle state
            break;
    }
}

/**
 * Initialize the IR servo system
 */
void ir_servo_initialize(void)
{
    // Store the PWM period
    totalPeriod = ((uint16_t)PWM1PRH << 8) | PWM1PRL;
    
    // Initialize state machine
    irServoState = IR_STATE_IDLE;
    itemNbr = 0;
    
    // Configure IR sensor interrupt to trigger state machine
    INT1_SetInterruptHandler(ir_servo_start);
    
    // Set TMR0 callback to our state machine handler
    TMR0_PeriodMatchCallbackRegister(TMR0_IRQHandler);
}

/**
 * Check if the IR servo state machine is busy processing
 */
bool ir_servo_is_busy(void)
{
    return (irServoState != IR_STATE_IDLE);
}

/**
 * Get the current item count
 */
uint8_t ir_servo_get_item_count(void)
{
    return itemNbr;
}

/**
 * Get the last measured weight
 */
uint16_t ir_servo_get_last_weight(void)
{
    return itemWeight;
}

/**
 * Get the minimum acceptable weight
 */
uint16_t ir_servo_get_min_weight(void)
{
    return weightMin;
}

/**
 * Get the maximum acceptable weight
 */
uint16_t ir_servo_get_max_weight(void)
{
    return weightMax;
}

/**
 * Set the minimum acceptable weight
 */
void ir_servo_set_min_weight(uint16_t min_weight)
{
    weightMin = min_weight;
}

/**
 * Set the maximum acceptable weight
 */
void ir_servo_set_max_weight(uint16_t max_weight)
{
    weightMax = max_weight;
}